commands:
  ping:
    command: ping {host}
    variables:
      - name: host
        type: string
        description: IP or Hostname
  traceroute:
    command: traceroute {host}
    variables:
      - name: host
        type: string
        description: IP or Hostname
  show_bgp_summary:
    command: show bgp summary
    variables: []
  show_bgp_neighbor:
    command: show bgp neighbors {neighbor}
    variables:
      - name: neighbor
        type: string
        description: BGP Neighbor IP
  show_bgp_ipv4_unicast_community:
    command: show bgp ipv4 unicast community {community}
    variables:
      - name: community
        type: string
        description: BGP Community
  show_bgp_ipv6_unicast_community:
    command: show bgp ipv6 unicast community {community}
    variables:
      - name: community
        type: string
        description: BGP Community

