groups:
  home:
    driver: eos
    username: admin
    password: Oeder-8140j
    allowed_commands:
      - ping
      - traceroute
      - show_bgp_neighbor
      - show_ip_bgp_prefix
      - show_ipv6_bgp_prefix
      - show_ip_bgp_community
      - show_ipv6_bgp_community
      - show_ip_bgp_as_path_regex
      - show_ipv6_bgp_as_path_regex


devices:
  - name: router1
    hostname: 172.31.1.11
    group: home
    allowed_commands:
      - show_bgp_summary
  - name: router2   
    hostname: 172.31.1.11
    group: home
