groups:
  eos:
    driver: eos
    username: test
    password: test
    allowed_commands:
      - ping
      - traceroute
      - show_bgp_neighbor
      - show_ip_bgp_prefix
      - show_ipv6_bgp_prefix
      - show_ip_bgp_community
      - show_bgp_ipv6_unicast_community
      - show_ip_bgp_as_path_regex
      - show_ipv6_bgp_regex
  nor1:
    parent: eos
  home:
    parent: eos

devices:
  - name: router1
    hostname: 172.31.1.11
    group: home
    allowed_commands:
      - show_bgp_summary
    disallowed_commands:
      - ping
      - traceroute
  - name: router2   
    hostname: 172.31.1.11
    group: home
  - name: router3
    hostname: 172.31.1.11
    group: nor1
    allowed_commands:
      - show_bgp_summary
    disallowed_commands:
      - ping
      - traceroute
  - name: router4
    hostname: 172.31.1.11
    group: nor1
