server {
    listen 80;
    server_name _;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /opt/bgplookingglass;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/opt/bgplookingglass/bgplookingglass.sock;
    }
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/ssl/certs/bgplookingglass.crt;
    ssl_certificate_key /etc/ssl/private/bgplookingglass.key;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /opt/bgplookingglass;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/opt/bgplookingglass/bgplookingglass.sock;
    }
}

